### PR TITLE
Infra + docs

### PR DESCRIPTION
**Pull request by ericmjl**
@asmirnov69 @samukweku, as promised, here is my first attempt at the infrastructure PR.

Here is a summary of my changes:

1. Added `environment.yml` for CI and local dev environments.
2. Added `mkdocs.yml` - configuration file for MkDocs.3. 
3. Renamed `doc/` to `docs/`.
5. Created a starter `index.md` file under `docs/`.
6. Added pre-commit hooks for code quality checks.
7. Satisfied part of the flake8 code checks by getting rid of unused imports.

We use pre-commit hooks to avoid having humans argue about routine code style and quality checks. Getting everyone to obey the robot can free our time to focus on higher-level discussions, like code organization. 

As things stand, the pre-commit hooks that will fail are:

1. flake8 - mostly lines being longer than 79 characters (79 chars are arbitrary; this number just matches what we have in pyjanitor).
2. interrogate - the code currently lacks docstrings.

I'm not worried about flake8 for the time being. On the other hand, if we can bring up docstring coverage, over time, that would be awesome! 

In a separate PR, I am happy to use tabnine to kickstart stuff (like we did on pandas-flavor) that you can fill in over time.

### CODE REVIEW

**Comment by asmirnov69** [comment]
Hi @ericmjl thanks for setting this important things up.
One more medium-size refactoring is coming from branch exp-objid, I can fix a lot of style and docstring problems as part of that - I can also merge your changes from main, so it is up to you to fix or not flake8 issues. 
Most important for me is to have project doc flow setup

**Comment by ericmjl** [comment]
Okie dokes, @asmirnov69 and @samukweku! I would love to get a 2nd pair of eyes on the PR for review. @samukweku if you're interested in how to configure our doc and gh-actions infra, this PR will probably give you a nicely self-contained view without other distractions. If you'd like to, please feel free to leave me questions on the tracker (or a loom video: https://www.loom.com).

**Review by samukweku — APPROVED** [review]

**Comment by asmirnov69** [comment]
@ericmjl I am reviewing this PR, trying to build docs using instructions from here https://pyjanitor-devs.github.io/pyjanitor/devguide/#build-docs-locally

**Comment by asmirnov69** [comment]
@ericmjl doc stream looks ok, `python -m mkdocs serve` works, so doc wiring flow is all set.
One question: what's the plan with github pages for pyjviz repo? can we do right after this PR is merged? I need stable links for some parts of documentation.

All other issues I will address on exp-objid branch as part of code refactoring.

**Review by asmirnov69 — COMMENTED** [review]
@ericmjl doc stream looks ok, `python -m mkdocs serve` works, so doc writing flow is all set.
One question: what's the plan with github pages for pyjviz repo? can we enable them for this project repo right after this PR is merged? I need stable links for some parts of documentation.

All other issues I will address on exp-objid branch as part of code refactoring.

**Review by asmirnov69 — APPROVED** [review]
i guess we will catch up later on publicly visible github pages for pyjviz

**Pull request merged**
